# Generated by Django 3.1.7 on 2021-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main',
            field=models.CharField(default='main', max_length=100, unique=True, verbose_name='Main Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.CharField(default='sub-category', max_length=100, unique=True, verbose_name='Sub Category name'),
        ),
    ]
