# Generated by Django 3.1.7 on 2021-08-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210808_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images'),
        ),
    ]
