# Generated by Django 3.1.7 on 2021-08-15 08:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210808_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Quiz_Qns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('qtn_type', models.CharField(choices=[('multipe', 'Multipe Choice'), ('text', 'Text'), ('choice', 'Choice')], max_length=20)),
                ('diff_level', models.CharField(blank=True, choices=[('beginer', 'Beginer/introduction'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('explanation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('hint', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ch_a', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice A')),
                ('ch_b', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice B')),
                ('ch_c', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice C')),
                ('ch_d', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice D')),
                ('ch_e', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice E')),
                ('ch_f', models.CharField(blank=True, max_length=2, null=True, verbose_name='Choice F')),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qna')),
            ],
            options={
                'verbose_name': 'Quiz_Qns',
                'verbose_name_plural': 'Quiz_Qns',
            },
        ),
    ]
