# Generated by Django 3.1.7 on 2021-08-20 03:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210815_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='qna',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='num_attempts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='pass_mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='pass_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice A'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice B'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice C'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice D'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice E'),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='ch_f',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice F'),
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(default='sub-category', max_length=100, unique=True, verbose_name='Sub Category name')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
            ],
            options={
                'verbose_name': 'Sub_Category',
                'verbose_name_plural': 'Sub_Category',
            },
        ),
    ]
