# Generated by Django 3.1.7 on 2021-08-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210820_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='updated',
        ),
        migrations.AddField(
            model_name='qna',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qna',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qna',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
