# Generated by Django 3.1.7 on 2021-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210824_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image_path', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email or Social media contact'),
        ),
    ]
