# Generated by Django 3.1.7 on 2021-08-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210824_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'Sub_Category', 'verbose_name_plural': 'Sub_Categories'},
        ),
    ]
