# Generated by Django 3.1.7 on 2021-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210828_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='short_desc',
            field=models.CharField(blank=True, default='Short quiz', max_length=255, null=True, verbose_name='Short description for search optimisation'),
        ),
    ]
