# Generated by Django 3.1.7 on 2021-09-06 08:43

import ckeditor.fields
from django.db import migrations
import imagekit.models.fields
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_qna_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'ordering': ['-created', 'num_attempts'], 'verbose_name': 'QnA', 'verbose_name_plural': 'QnAs'},
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=quiz.models.image_path),
        ),
        migrations.AlterField(
            model_name='qna',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Note to guide or assist those taking the quiz'),
        ),
    ]
