# Generated by Django 3.1.7 on 2021-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210906_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='short_desc',
            field=models.CharField(blank=True, default='Short quiz', max_length=255, null=True, verbose_name='Short description/abstract for search optimisation'),
        ),
    ]
