# Generated by Django 3.1.7 on 2021-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20210908_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_qns',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
