# Generated by Django 3.1.7 on 2021-08-25 03:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email or Social media contact')),
                ('firm_bio', models.TextField(blank=True, null=True, verbose_name='Tell us about your firm')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email or Social media contact')),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='image_path', verbose_name='Organisation logo')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hr_firm',
                'verbose_name_plural': 'Hr_firms',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Name')),
                ('about_me', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Name')),
                ('contact', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='image_path', verbose_name='Profile picture')),
                ('resume', models.FileField(upload_to='image_path')),
                ('cover_letter', models.TextField(verbose_name='Your Cover letter')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
            },
        ),
    ]
