# Generated by Django 3.1.7 on 2021-08-25 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Your agency's name")),
                ('slug', models.SlugField()),
                ('firm_bio', models.TextField(blank=True, null=True, verbose_name='Tell us about your firm')),
                ('contact', models.CharField(max_length=255, verbose_name='Email or Social media contact')),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='image_path', verbose_name='Organisation logo')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency_firm',
                'verbose_name_plural': 'Agency_firms',
            },
        ),
        migrations.AlterField(
            model_name='applicant',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='A short bio about myself'),
        ),
        migrations.DeleteModel(
            name='Hr_firm',
        ),
    ]
