# Generated by Django 3.1.7 on 2021-08-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210828_0700'),
        ('hrquiz', '0002_auto_20210825_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.EmailField(max_length=254, verbose_name='Your email address'),
        ),
        migrations.CreateModel(
            name='Quiz_profile',
            fields=[
                ('qna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.qna')),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description for search optimisation')),
                ('private', models.BooleanField(default=False)),
                ('icreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.agency_firm')),
            ],
            options={
                'verbose_name': 'Quiz_profile',
                'verbose_name_plural': 'Quiz_profiles',
            },
            bases=('quiz.qna',),
        ),
        migrations.CreateModel(
            name='Interview_quiz',
            fields=[
                ('quiz_qns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.quiz_qns')),
                ('iquiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.quiz_profile')),
            ],
            options={
                'verbose_name': 'Interview_quiz',
                'verbose_name_plural': 'Interview_quizzes',
            },
            bases=('quiz.quiz_qns',),
        ),
        migrations.CreateModel(
            name='Applicant_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.applicant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.quiz_profile')),
            ],
            options={
                'verbose_name': 'Applicant_score',
                'verbose_name_plural': 'Applicant_scores',
            },
        ),
    ]
