# Generated by Django 3.1.7 on 2021-08-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210828_0700'),
        ('hrquiz', '0004_auto_20210828_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview_quiz',
            name='iquiz_name',
        ),
        migrations.RemoveField(
            model_name='interview_quiz',
            name='quiz_qns_ptr',
        ),
        migrations.RemoveField(
            model_name='quiz_profile',
            name='icreator',
        ),
        migrations.RemoveField(
            model_name='quiz_profile',
            name='qna_ptr',
        ),
        migrations.DeleteModel(
            name='Applicant_score',
        ),
        migrations.DeleteModel(
            name='Interview_quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_profile',
        ),
    ]
