# Generated by Django 3.1.7 on 2021-08-28 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_editorjs_fields.fields
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrquiz', '0005_auto_20210828_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('short_desc', models.CharField(default='Short quiz', max_length=255, verbose_name='Short description for search optimisation')),
                ('description', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('question_file', models.JSONField(blank=True, default=quiz.models.my_default, null=True)),
                ('resource_link', models.CharField(blank=True, max_length=150, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('answers_file', models.JSONField(blank=True, default=quiz.models.my_default, null=True)),
                ('summary_result', models.JSONField(blank=True, default=quiz.models.my_default, null=True)),
                ('avg_results', models.PositiveIntegerField(blank=True, null=True)),
                ('num_attempts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pass_mark', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pass_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.agency_firm')),
            ],
            options={
                'verbose_name': 'Quiz_profile',
                'verbose_name_plural': 'Quiz_profiles',
            },
        ),
    ]
