# Generated by Django 3.1.7 on 2021-08-28 08:48

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hrquiz', '0006_quiz_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('qtn_type', models.CharField(choices=[('multipe', 'Multipe Choice'), ('text', 'Text'), ('choice', 'Choice')], max_length=20)),
                ('diff_level', models.CharField(blank=True, choices=[('beginer', 'Beginer/introduction'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('question', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Correct answer')),
                ('explanation', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('hint', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('ch_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice A')),
                ('ch_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice B')),
                ('ch_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice C')),
                ('ch_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice D')),
                ('ch_e', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice E')),
                ('ch_f', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choice F')),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.quiz_profile')),
            ],
            options={
                'verbose_name': 'Interview_quiz',
                'verbose_name_plural': 'Interview_quizs',
            },
        ),
    ]
