# Generated by Django 3.1.7 on 2021-08-28 08:49

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrquiz', '0007_interview_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('answers', models.JSONField(blank=True, default=quiz.models.my_default, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.applicant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrquiz.quiz_profile')),
            ],
            options={
                'verbose_name': 'Applicant_score',
                'verbose_name_plural': 'Applicant_scores',
            },
        ),
    ]
