# Generated by Django 3.1.7 on 2021-08-28 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrquiz', '0008_applicant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_quiz',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview_quiz',
            name='hint',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview_quiz',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_profile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
