# Generated by Django 3.1.7 on 2021-09-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrquiz', '0009_auto_20210828_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz_profile',
            options={'verbose_name': 'Job_profile', 'verbose_name_plural': 'Job_profiles'},
        ),
    ]
